/**
 * CHAMPIONSITO — rose.js
 * Rose delle 36 squadre della fase a campionato UCL 2026/27, da API ESPN,
 * scaricate il 2026-09-05. Chiave = id squadra di calendario-ufficiale.js.
 * p: G portiere, D difensore, M centrocampista, F attaccante.
 */
export const ROSE = {
  // sq01 — Paris Saint-Germain (ESPN 160, fra.1) — 24 giocatori
  sq01: [
    { n: 'Lucas Chevalier', p: 'G' },
    { n: 'Alessandro Longoni', p: 'G' },
    { n: 'Matvei Safonov', p: 'G' },
    { n: 'Lucas Beraldo', p: 'D' },
    { n: 'Lucas Digne', p: 'D' },
    { n: 'Achraf Hakimi', p: 'D' },
    { n: 'Lucas Hernández', p: 'D' },
    { n: 'Marquinhos', p: 'D' },
    { n: 'Nuno Mendes', p: 'D' },
    { n: 'Willian Pacho', p: 'D' },
    { n: 'Illia Zabarnyi', p: 'D' },
    { n: 'Maghnes Akliouche', p: 'M' },
    { n: 'Dro Fernández', p: 'M' },
    { n: 'Senny Mayulu', p: 'M' },
    { n: 'João Neves', p: 'M' },
    { n: 'Fabián Ruiz', p: 'M' },
    { n: 'Vitinha', p: 'M' },
    { n: 'Warren Zaïre-Emery', p: 'M' },
    { n: 'Ousmane Dembélé', p: 'F' },
    { n: 'Désiré Doué', p: 'F' },
    { n: 'Mika Godts', p: 'F' },
    { n: 'Khvicha Kvaratskhelia', p: 'F' },
    { n: 'Quentin Ndjantou', p: 'F' },
    { n: 'Ferran Torres', p: 'F' },
  ],

  // sq02 — Bayern Munich (ESPN 132, ger.1) — 24 giocatori
  sq02: [
    { n: 'Manuel Neuer', p: 'G' },
    { n: 'Sven Ulreich', p: 'G' },
    { n: 'Jonas Urbig', p: 'G' },
    { n: 'Nathaniel Brown', p: 'D' },
    { n: 'Alphonso Davies', p: 'D' },
    { n: 'Hiroki Ito', p: 'D' },
    { n: 'Kim Min-Jae', p: 'D' },
    { n: 'Josip Stanisic', p: 'D' },
    { n: 'Jonathan Tah', p: 'D' },
    { n: 'Dayot Upamecano', p: 'D' },
    { n: 'Tom Bischof', p: 'M' },
    { n: 'Maycon Cardozo', p: 'M' },
    { n: 'David Daiber', p: 'M' },
    { n: 'Lennart Karl', p: 'M' },
    { n: 'Joshua Kimmich', p: 'M' },
    { n: 'Konrad Laimer', p: 'M' },
    { n: 'Jamal Musiala', p: 'M' },
    { n: 'Bara Sapoko Ndiaye', p: 'M' },
    { n: 'Michael Olise', p: 'M' },
    { n: 'Aleksandar Pavlovic', p: 'M' },
    { n: 'Ismael Saibari', p: 'M' },
    { n: 'Luis Díaz', p: 'F' },
    { n: 'Serge Gnabry', p: 'F' },
    { n: 'Harry Kane', p: 'F' },
  ],

  // sq03 — Real Madrid (ESPN 86, esp.1) — 32 giocatori
  sq03: [
    { n: 'Thibaut Courtois', p: 'G' },
    { n: 'Andriy Lunin', p: 'G' },
    { n: 'Sergio Mestre', p: 'G' },
    { n: 'Javier Navarro', p: 'G' },
    { n: 'Trent Alexander-Arnold', p: 'D' },
    { n: 'Raúl Asencio', p: 'D' },
    { n: 'Álvaro Carreras', p: 'D' },
    { n: 'Marc Cucurella', p: 'D' },
    { n: 'Denzel Dumfries', p: 'D' },
    { n: 'Dean Huijsen', p: 'D' },
    { n: 'Ibrahima Konaté', p: 'D' },
    { n: 'Ferland Mendy', p: 'D' },
    { n: 'Éder Militão', p: 'D' },
    { n: 'Antonio Rüdiger', p: 'D' },
    { n: 'Jude Bellingham', p: 'M' },
    { n: 'Eduardo Camavinga', p: 'M' },
    { n: 'Jorge Cestero', p: 'M' },
    { n: 'Alexis Ciria', p: 'M' },
    { n: 'Brahim Díaz', p: 'M' },
    { n: 'Arda Güler', p: 'M' },
    { n: 'Sergio Martínez', p: 'M' },
    { n: 'Thiago Pitarch', p: 'M' },
    { n: 'Bernardo Silva', p: 'M' },
    { n: 'Aurélien Tchouaméni', p: 'M' },
    { n: 'Federico Valverde', p: 'M' },
    { n: 'Yan Diomande', p: 'F' },
    { n: 'Endrick', p: 'F' },
    { n: 'Carlos Espí', p: 'F' },
    { n: 'Vinícius Júnior', p: 'F' },
    { n: 'Kylian Mbappé', p: 'F' },
    { n: 'Mario Rivas', p: 'F' },
    { n: 'Rodrygo', p: 'F' },
  ],

  // sq04 — Liverpool (ESPN 364, eng.1) — 29 giocatori
  sq04: [
    { n: 'Alisson Becker', p: 'G' },
    { n: 'Harvey Davies', p: 'G' },
    { n: 'Vitezslav Jaros', p: 'G' },
    { n: 'Giorgi Mamardashvili', p: 'G' },
    { n: 'Freddie Woodman', p: 'G' },
    { n: 'Ronald Araújo', p: 'D' },
    { n: 'Conor Bradley', p: 'D' },
    { n: 'Virgil van Dijk', p: 'D' },
    { n: 'Jeremie Frimpong', p: 'D' },
    { n: 'Joe Gomez', p: 'D' },
    { n: 'Jérémy Jacquet', p: 'D' },
    { n: 'Milos Kerkez', p: 'D' },
    { n: 'Giovanni Leoni', p: 'D' },
    { n: 'Kostas Tsimikas', p: 'D' },
    { n: 'Alexis Mac Allister', p: 'M' },
    { n: 'Wataru Endo', p: 'M' },
    { n: 'Ryan Gravenberch', p: 'M' },
    { n: 'James McConnell', p: 'M' },
    { n: 'Trey Nyoni', p: 'M' },
    { n: 'Dominik Szoboszlai', p: 'M' },
    { n: 'Florian Wirtz', p: 'M' },
    { n: 'Bradley Barcola', p: 'F' },
    { n: 'Federico Chiesa', p: 'F' },
    { n: 'Hugo Ekitike', p: 'F' },
    { n: 'Cody Gakpo', p: 'F' },
    { n: 'Alexander Isak', p: 'F' },
    { n: 'Lewis Koumas', p: 'F' },
    { n: 'Víctor Muñoz', p: 'F' },
    { n: 'Rio Ngumoha', p: 'F' },
  ],

  // sq05 — Inter (ESPN 110, ita.1) — 28 giocatori
  sq05: [
    { n: 'Raffaele Di Gennaro', p: 'G' },
    { n: 'Josep Martínez', p: 'G' },
    { n: 'Ivan Provedel', p: 'G' },
    { n: 'Piotr Zieliński', p: 'G' },
    { n: 'Manuel Akanji', p: 'D' },
    { n: 'Carlos Augusto', p: 'D' },
    { n: 'Alessandro Bastoni', p: 'D' },
    { n: 'Yann Bisseck', p: 'D' },
    { n: 'Leonardo Bovio', p: 'D' },
    { n: 'Federico Dimarco', p: 'D' },
    { n: 'Benjamin Pavard', p: 'D' },
    { n: 'Djed Spence', p: 'D' },
    { n: 'John Stones', p: 'D' },
    { n: 'Nicolò Barella', p: 'M' },
    { n: 'Hakan Çalhanoglu', p: 'M' },
    { n: 'Andy Diouf', p: 'M' },
    { n: 'Curtis Jones', p: 'M' },
    { n: 'Mattia Marello', p: 'M' },
    { n: 'Henrikh Mkhitaryan', p: 'M' },
    { n: 'Aleksandar Stankovic', p: 'M' },
    { n: 'Petar Sucic', p: 'M' },
    { n: 'Ange-Yoan Bonny', p: 'F' },
    { n: 'Pio Esposito', p: 'F' },
    { n: 'Luis Henrique', p: 'F' },
    { n: 'Jamal Iddrissou', p: 'F' },
    { n: 'Lautaro Martínez', p: 'F' },
    { n: 'Mattia Mosconi', p: 'F' },
    { n: 'Marcus Thuram', p: 'F' },
  ],

  // sq06 — Manchester City (ESPN 382, eng.1) — 26 giocatori
  sq06: [
    { n: 'Marcus Bettinelli', p: 'G' },
    { n: 'Gianluigi Donnarumma', p: 'G' },
    { n: 'Gerónimo Rulli', p: 'G' },
    { n: 'Rayan Aït-Nouri', p: 'D' },
    { n: 'Kaden Braithwaite', p: 'D' },
    { n: 'Rúben Dias', p: 'D' },
    { n: 'Marc Guéhi', p: 'D' },
    { n: 'Josko Gvardiol', p: 'D' },
    { n: 'Abdukodir Khusanov', p: 'D' },
    { n: 'Rico Lewis', p: 'D' },
    { n: 'Nico O\'Reilly', p: 'D' },
    { n: 'Vitor Reis', p: 'D' },
    { n: 'Josh Wilson-Esbrand', p: 'D' },
    { n: 'Elliot Anderson', p: 'M' },
    { n: 'Ayyoub Bouaddi', p: 'M' },
    { n: 'Rayan Cherki', p: 'M' },
    { n: 'Enzo Fernández', p: 'M' },
    { n: 'Phil Foden', p: 'M' },
    { n: 'Mateo Kovacic', p: 'M' },
    { n: 'Matheus Nunes', p: 'M' },
    { n: 'Jérémy Doku', p: 'F' },
    { n: 'Allan Elias', p: 'F' },
    { n: 'Erling Haaland', p: 'F' },
    { n: 'Ryan McAidoo', p: 'F' },
    { n: 'Iliman Ndiaye', p: 'F' },
    { n: 'Antoine Semenyo', p: 'F' },
  ],

  // sq07 — Arsenal (ESPN 359, eng.1) — 24 giocatori
  sq07: [
    { n: 'Kepa Arrizabalaga', p: 'G' },
    { n: 'Illan Meslier', p: 'G' },
    { n: 'David Raya', p: 'G' },
    { n: 'Riccardo Calafiori', p: 'D' },
    { n: 'Piero Hincapié', p: 'D' },
    { n: 'Ezri Konsa', p: 'D' },
    { n: 'Myles Lewis-Skelly', p: 'D' },
    { n: 'Gabriel Magalhães', p: 'D' },
    { n: 'Cristhian Mosquera', p: 'D' },
    { n: 'William Saliba', p: 'D' },
    { n: 'Jurriën Timber', p: 'D' },
    { n: 'Ben White', p: 'D' },
    { n: 'Max Dowman', p: 'M' },
    { n: 'Eberechi Eze', p: 'M' },
    { n: 'Bruno Guimarães', p: 'M' },
    { n: 'Mikel Merino', p: 'M' },
    { n: 'Martin Ødegaard', p: 'M' },
    { n: 'Declan Rice', p: 'M' },
    { n: 'Martín Zubimendi', p: 'M' },
    { n: 'Viktor Gyökeres', p: 'F' },
    { n: 'Kai Havertz', p: 'F' },
    { n: 'Noni Madueke', p: 'F' },
    { n: 'Bukayo Saka', p: 'F' },
    { n: 'Christos Tzolis', p: 'F' },
  ],

  // sq08 — Barcelona (ESPN 83, esp.1) — 29 giocatori
  sq08: [
    { n: 'Eder Aller', p: 'G' },
    { n: 'Joan García', p: 'G' },
    { n: 'Dominik Livakovic', p: 'G' },
    { n: 'Wojciech Szczesny', p: 'G' },
    { n: 'Alejandro Balde', p: 'D' },
    { n: 'João Cancelo', p: 'D' },
    { n: 'Andreas Christensen', p: 'D' },
    { n: 'Pau Cubarsí', p: 'D' },
    { n: 'Xavi Espart', p: 'D' },
    { n: 'Eric García', p: 'D' },
    { n: 'Jules Koundé', p: 'D' },
    { n: 'Gerard Martín', p: 'D' },
    { n: 'Jordi Pesquer', p: 'D' },
    { n: 'Marc Bernal', p: 'M' },
    { n: 'Brian Fariñas', p: 'M' },
    { n: 'Gavi', p: 'M' },
    { n: 'Frenkie de Jong', p: 'M' },
    { n: 'Fermín López', p: 'M' },
    { n: 'Dani Olmo', p: 'M' },
    { n: 'Pedri', p: 'M' },
    { n: 'Rodri', p: 'M' },
    { n: 'Hamza Abdelkarim', p: 'F' },
    { n: 'Karim Adeyemi', p: 'F' },
    { n: 'Roony Bardghji', p: 'F' },
    { n: 'Jesse Bisiwu', p: 'F' },
    { n: 'Anthony Gordon', p: 'F' },
    { n: 'Gabriel Jesus', p: 'F' },
    { n: 'Raphinha', p: 'F' },
    { n: 'Lamine Yamal', p: 'F' },
  ],

  // sq09 — Atlético Madrid (ESPN 1068, esp.1) — 28 giocatori
  sq09: [
    { n: 'Salvi Esquivel', p: 'G' },
    { n: 'Juan Musso', p: 'G' },
    { n: 'Jan Oblak', p: 'G' },
    { n: 'Jorge Domínguez', p: 'D' },
    { n: 'Alejandro Grimaldo', p: 'D' },
    { n: 'Dávid Hancko', p: 'D' },
    { n: 'Daniel Martinez', p: 'D' },
    { n: 'Robin Le Normand', p: 'D' },
    { n: 'Marc Pubill', p: 'D' },
    { n: 'Cristian Romero', p: 'D' },
    { n: 'Álex Baena', p: 'M' },
    { n: 'Pablo Barrios', p: 'M' },
    { n: 'Johnny Cardoso', p: 'M' },
    { n: 'Jorge Castillo', p: 'M' },
    { n: 'Morten Hjulmand', p: 'M' },
    { n: 'Lee Kang-In', p: 'M' },
    { n: 'Koke', p: 'M' },
    { n: 'Marcos Llorente', p: 'M' },
    { n: 'Rodrigo Mendoza', p: 'M' },
    { n: 'Obed Vargas', p: 'M' },
    { n: 'Julián Álvarez', p: 'F' },
    { n: 'Miguel Cubo', p: 'F' },
    { n: 'Jonathan David', p: 'F' },
    { n: 'Ademola Lookman', p: 'F' },
    { n: 'Carlos Martín', p: 'F' },
    { n: 'Arnau Ortiz', p: 'F' },
    { n: 'Giuliano Simeone', p: 'F' },
    { n: 'Alexander Sørloth', p: 'F' },
  ],

  // sq10 — Borussia Dortmund (ESPN 124, ger.1) — 30 giocatori
  sq10: [
    { n: 'Patrick Drewes', p: 'G' },
    { n: 'Gregor Kobel', p: 'G' },
    { n: 'Alexander Meyer', p: 'G' },
    { n: 'Silas Ostrzinski', p: 'G' },
    { n: 'Waldemar Anton', p: 'D' },
    { n: 'Ramy Bensebaini', p: 'D' },
    { n: 'Kouakou Gadou', p: 'D' },
    { n: 'Filippo Mané', p: 'D' },
    { n: 'Kauã Prates', p: 'D' },
    { n: 'Luca Reggiani', p: 'D' },
    { n: 'Julian Ryerson', p: 'D' },
    { n: 'Nico Schlotterbeck', p: 'D' },
    { n: 'Daniel Svensson', p: 'D' },
    { n: 'Jobe Bellingham', p: 'M' },
    { n: 'Emre Can', p: 'M' },
    { n: 'Carney Chukwuemeka', p: 'M' },
    { n: 'Mussa Kaba', p: 'M' },
    { n: 'Konstantinos Karetsas', p: 'M' },
    { n: 'Giannis Konstantelias', p: 'M' },
    { n: 'Justin Lerma', p: 'M' },
    { n: 'Felix Nmecha', p: 'M' },
    { n: 'Ethan Nwaneri', p: 'M' },
    { n: 'Marcel Sabitzer', p: 'M' },
    { n: 'Enzo De Pina Duarte Dos Santos', p: 'M' },
    { n: 'Joey Veerman', p: 'M' },
    { n: 'Mathis Albert', p: 'F' },
    { n: 'Maximilian Beier', p: 'F' },
    { n: 'Serhou Guirassy', p: 'F' },
    { n: 'Samuele Inácio', p: 'F' },
    { n: 'Fábio Silva', p: 'F' },
  ],

  // sq11 — Roma (ESPN 104, ita.1) — 27 giocatori
  sq11: [
    { n: 'Pierluigi Gollini', p: 'G' },
    { n: 'Alessio Marcaccini', p: 'G' },
    { n: 'Giorgio De Marzi', p: 'G' },
    { n: 'Mile Svilar', p: 'G' },
    { n: 'Devis Vásquez', p: 'G' },
    { n: 'Leonardo Balerdi', p: 'D' },
    { n: 'Daniele Ghilardi', p: 'D' },
    { n: 'Mario Hermoso', p: 'D' },
    { n: 'Konstantinos Koulierakis', p: 'D' },
    { n: 'Emanuele Lulli', p: 'D' },
    { n: 'Gianluca Mancini', p: 'D' },
    { n: 'Nahuel Molina', p: 'D' },
    { n: 'Evan Ndicka', p: 'D' },
    { n: 'Devyne Rensch', p: 'D' },
    { n: 'Anass Salah-Eddine', p: 'D' },
    { n: 'Wesley', p: 'D' },
    { n: 'Bryan Cristante', p: 'M' },
    { n: 'Manu Koné', p: 'M' },
    { n: 'Rodrigo Mora', p: 'M' },
    { n: 'Lorenzo Pellegrini', p: 'M' },
    { n: 'Niccolò Pisilli', p: 'M' },
    { n: 'Marten de Roon', p: 'M' },
    { n: 'Antonio Arena', p: 'F' },
    { n: 'Santiago Castro', p: 'F' },
    { n: 'Paulo Dybala', p: 'F' },
    { n: 'Donyell Malen', p: 'F' },
    { n: 'Matìas Soulè', p: 'F' },
  ],

  // sq12 — Sporting CP (ESPN 2250, por.1) — 29 giocatori
  sq12: [
    { n: 'Diego Callai', p: 'G' },
    { n: 'Kaique', p: 'G' },
    { n: 'Francisco Silva', p: 'G' },
    { n: 'Rui Silva', p: 'G' },
    { n: 'Ibrahima Ba', p: 'D' },
    { n: 'Zeno Debast', p: 'D' },
    { n: 'Rodrigo Dias', p: 'D' },
    { n: 'Iván Fresneda', p: 'D' },
    { n: 'Gonçalo Inácio', p: 'D' },
    { n: 'Eduardo Quaresma', p: 'D' },
    { n: 'Nuno Santos', p: 'D' },
    { n: 'Georgios Vagiannidis', p: 'D' },
    { n: 'Moncef Zekri', p: 'D' },
    { n: 'Sergi Altimira', p: 'M' },
    { n: 'Silas Andersen', p: 'M' },
    { n: 'Maxi Araújo', p: 'M' },
    { n: 'Geny Catamo', p: 'M' },
    { n: 'Issa Doumbia', p: 'M' },
    { n: 'Eduardo Felicíssimo', p: 'M' },
    { n: 'Pedro Lima', p: 'M' },
    { n: 'João Simões', p: 'M' },
    { n: 'Rodrigo Zalazar', p: 'M' },
    { n: 'Jesse Derry', p: 'F' },
    { n: 'Flávio Gonçalves', p: 'F' },
    { n: 'Luis Guilherme', p: 'F' },
    { n: 'Fotis Ioannidis', p: 'F' },
    { n: 'Nestory Irankunda', p: 'F' },
    { n: 'Rafael Nel', p: 'F' },
    { n: 'Luis Suárez', p: 'F' },
  ],

  // sq13 — Aston Villa (ESPN 362, eng.1) — 29 giocatori
  sq13: [
    { n: 'Owen Asemota', p: 'G' },
    { n: 'Marco Bizot', p: 'G' },
    { n: 'Zion Suzuki', p: 'G' },
    { n: 'James Wright', p: 'G' },
    { n: 'Matty Cash', p: 'D' },
    { n: 'Modou Cissé', p: 'D' },
    { n: 'Taylor Harwood-Bellis', p: 'D' },
    { n: 'Victor Lindelöf', p: 'D' },
    { n: 'Ian Maatsen', p: 'D' },
    { n: 'Tyrone Mings', p: 'D' },
    { n: 'Matteo Ruggeri', p: 'D' },
    { n: 'Pau Torres', p: 'D' },
    { n: 'Aaron Wan-Bissaka', p: 'D' },
    { n: 'Ross Barkley', p: 'M' },
    { n: 'Lamare Bogarde', p: 'M' },
    { n: 'Emiliano Buendía', p: 'M' },
    { n: 'João Gomes', p: 'M' },
    { n: 'Leon Goretzka', p: 'M' },
    { n: 'George Hemmings', p: 'M' },
    { n: 'Boubacar Kamara', p: 'M' },
    { n: 'Johan Manzambi', p: 'M' },
    { n: 'John McGinn', p: 'M' },
    { n: 'Amadou Onana', p: 'M' },
    { n: 'Tammy Abraham', p: 'F' },
    { n: 'Alysson', p: 'F' },
    { n: 'Alejandro Garnacho', p: 'F' },
    { n: 'Nicolas Jackson', p: 'F' },
    { n: 'Brian Madjo', p: 'F' },
    { n: 'Ibrahim Mbaye', p: 'F' },
  ],

  // sq14 — Porto (ESPN 437, por.1) — 31 giocatori
  sq14: [
    { n: 'João Afonso', p: 'G' },
    { n: 'Diogo Costa', p: 'G' },
    { n: 'João Costa', p: 'G' },
    { n: 'Cláudio Ramos', p: 'G' },
    { n: 'Jan Bednarek', p: 'D' },
    { n: 'Alberto Costa', p: 'D' },
    { n: 'Martim Fernandes', p: 'D' },
    { n: 'Jakub Kiwior', p: 'D' },
    { n: 'Moura', p: 'D' },
    { n: 'Nehuén Pérez', p: 'D' },
    { n: 'Dominik Prpic', p: 'D' },
    { n: 'Zaidu Sanusi', p: 'D' },
    { n: 'Souza', p: 'D' },
    { n: 'Seko Fofana', p: 'M' },
    { n: 'Victor Froholdt', p: 'M' },
    { n: 'Hwang In-Beom', p: 'M' },
    { n: 'Pablo Rosario', p: 'M' },
    { n: 'Tiago Silva', p: 'M' },
    { n: 'Vasco Sousa', p: 'M' },
    { n: 'Alan Varela', p: 'M' },
    { n: 'Gabri Veiga', p: 'M' },
    { n: 'Samu Aghehowa', p: 'F' },
    { n: 'Duarte Cunha', p: 'F' },
    { n: 'Eduardo Ferreira', p: 'F' },
    { n: 'Santiago Gimenez', p: 'F' },
    { n: 'William Gomes', p: 'F' },
    { n: 'Gabriel Mec', p: 'F' },
    { n: 'Pepê', p: 'F' },
    { n: 'Oskar Pietuszewski', p: 'F' },
    { n: 'Borja Sainz', p: 'F' },
    { n: 'André Silva', p: 'F' },
  ],

  // sq15 — Manchester United (ESPN 360, eng.1) — 30 giocatori
  sq15: [
    { n: 'Karl Darlow', p: 'G' },
    { n: 'Tom Heaton', p: 'G' },
    { n: 'Senne Lammens', p: 'G' },
    { n: 'Dermot Mee', p: 'G' },
    { n: 'Harry Amass', p: 'D' },
    { n: 'Diogo Dalot', p: 'D' },
    { n: 'Patrick Dorgu', p: 'D' },
    { n: 'Ayden Heaven', p: 'D' },
    { n: 'Matthijs de Ligt', p: 'D' },
    { n: 'Harry Maguire', p: 'D' },
    { n: 'Lisandro Martínez', p: 'D' },
    { n: 'Noussair Mazraoui', p: 'D' },
    { n: 'Luke Shaw', p: 'D' },
    { n: 'Leny Yoro', p: 'D' },
    { n: 'Carlos Baleba', p: 'M' },
    { n: 'Bruno Fernandes', p: 'M' },
    { n: 'Jack Fletcher', p: 'M' },
    { n: 'Tyler Fletcher', p: 'M' },
    { n: 'Kobbie Mainoo', p: 'M' },
    { n: 'Mason Mount', p: 'M' },
    { n: 'Andrey Santos', p: 'M' },
    { n: 'Youri Tielemans', p: 'M' },
    { n: 'Manuel Ugarte', p: 'M' },
    { n: 'Matheus Cunha', p: 'F' },
    { n: 'Amad Diallo', p: 'F' },
    { n: 'Shea Lacey', p: 'F' },
    { n: 'Bryan Mbeumo', p: 'F' },
    { n: 'Marcus Rashford', p: 'F' },
    { n: 'Benjamin Sesko', p: 'F' },
    { n: 'Joshua Zirkzee', p: 'F' },
  ],

  // sq16 — Club Brugge (ESPN 570, bel.1) — 29 giocatori
  sq16: [
    { n: 'Axl De Corte', p: 'G' },
    { n: 'Argus Driessche', p: 'G' },
    { n: 'Nordin Jackers', p: 'G' },
    { n: 'Yann Sommer', p: 'G' },
    { n: 'Samba Coulibaly', p: 'D' },
    { n: 'Matteo Dams', p: 'D' },
    { n: 'Lee Han-Beom', p: 'D' },
    { n: 'Brandon Mechele', p: 'D' },
    { n: 'Joel Ordóñez', p: 'D' },
    { n: 'Kyriani Sabbe', p: 'D' },
    { n: 'Joaquin Seys', p: 'D' },
    { n: 'Hugo Siquet', p: 'D' },
    { n: 'Jorne Spileers', p: 'D' },
    { n: 'Wout Verlinden', p: 'D' },
    { n: 'Lynnt Audoor', p: 'M' },
    { n: 'Tian Nai Koren', p: 'M' },
    { n: 'Felix Lemarechal', p: 'M' },
    { n: 'Gianluca Okon-Engstler', p: 'M' },
    { n: 'Freddie Potts', p: 'M' },
    { n: 'Cheveyo Tsawa', p: 'M' },
    { n: 'Hans Vanaken', p: 'M' },
    { n: 'Hugo Vetlesen', p: 'M' },
    { n: 'Mamadou Diakhon', p: 'F' },
    { n: 'Carlos Forbs', p: 'F' },
    { n: 'Wisdom Mike', p: 'F' },
    { n: 'Nicolo Tresoldi', p: 'F' },
    { n: 'Andrej Vasovic', p: 'F' },
    { n: 'Romeo Vermant', p: 'F' },
    { n: 'Jan Virgili', p: 'F' },
  ],

  // sq17 — Real Betis (ESPN 244, esp.1) — 28 giocatori
  sq17: [
    { n: 'Diego Conde', p: 'G' },
    { n: 'Manu González', p: 'G' },
    { n: 'Álvaro De Pablo', p: 'G' },
    { n: 'Álvaro Valles', p: 'G' },
    { n: 'Marc Bartra', p: 'D' },
    { n: 'Héctor Bellerín', p: 'D' },
    { n: 'Junior Firpo', p: 'D' },
    { n: 'Fran García', p: 'D' },
    { n: 'Valentín Gómez', p: 'D' },
    { n: 'Diego Llorente', p: 'D' },
    { n: 'Natan', p: 'D' },
    { n: 'Ángel Ortiz', p: 'D' },
    { n: 'Facundo Bernal', p: 'M' },
    { n: 'Dani Ceballos', p: 'M' },
    { n: 'Giovani Lo Celso', p: 'M' },
    { n: 'Nelson Deossa', p: 'M' },
    { n: 'Álvaro Fidalgo', p: 'M' },
    { n: 'Pablo Fornals', p: 'M' },
    { n: 'Isco', p: 'M' },
    { n: 'Rodrigo Riquelme', p: 'M' },
    { n: 'Marc Roca', p: 'M' },
    { n: 'Antony', p: 'F' },
    { n: 'Abde Ezzalzouli', p: 'F' },
    { n: 'Cucho Hernández', p: 'F' },
    { n: 'Iker Losada', p: 'F' },
    { n: 'José Morante', p: 'F' },
    { n: 'Troy Parrott', p: 'F' },
    { n: 'Aitor Ruibal', p: 'F' },
  ],

  // sq18 — PSV Eindhoven (ESPN 148, ned.1) — 31 giocatori
  sq18: [
    { n: 'Matej Kovár', p: 'G' },
    { n: 'Khadim Ngom', p: 'G' },
    { n: 'Nick Olij', p: 'G' },
    { n: 'Tijn Smolenaars', p: 'G' },
    { n: 'Sergiño Dest', p: 'D' },
    { n: 'Ryan Flamingo', p: 'D' },
    { n: 'Yarek Gasiorowski', p: 'D' },
    { n: 'Lutsharel Geertruida', p: 'D' },
    { n: 'Mauro Júnior', p: 'D' },
    { n: 'Fabian Merién', p: 'D' },
    { n: 'Armando Obispo', p: 'D' },
    { n: 'Kiliann Sildillia', p: 'D' },
    { n: 'Shuryjano Cornecion', p: 'M' },
    { n: 'Noah Fernandez', p: 'M' },
    { n: 'Filip Kostic', p: 'M' },
    { n: 'Sven Mijnans', p: 'M' },
    { n: 'Kodai Sano', p: 'M' },
    { n: 'Ayoni Santos', p: 'M' },
    { n: 'Jerdy Schouten', p: 'M' },
    { n: 'Guus Til', p: 'M' },
    { n: 'Paul Wanner', p: 'M' },
    { n: 'Esmir Bajraktarevic', p: 'F' },
    { n: 'Ruben Van Bommel', p: 'F' },
    { n: 'Amir Bouhamdi', p: 'F' },
    { n: 'Mikkel Hansen', p: 'F' },
    { n: 'Sam Lammers', p: 'F' },
    { n: 'Dennis Man', p: 'F' },
    { n: 'Sami Ouaissa', p: 'F' },
    { n: 'Ricardo Pepi', p: 'F' },
    { n: 'Ivan Perisic', p: 'F' },
    { n: 'Alassane Pléa', p: 'F' },
  ],

  // sq19 — Feyenoord (ESPN 142, ned.1) — 31 giocatori
  sq19: [
    { n: 'Mannou Berger', p: 'G' },
    { n: 'Liam Bossin', p: 'G' },
    { n: 'Tjark Ernst', p: 'G' },
    { n: 'Florian Kastenmeier', p: 'G' },
    { n: 'Thomas Beelen', p: 'D' },
    { n: 'Jordan Bos', p: 'D' },
    { n: 'Mats Deijl', p: 'D' },
    { n: 'Jerry St. Juste', p: 'D' },
    { n: 'Javi López', p: 'D' },
    { n: 'Mika Mármol', p: 'D' },
    { n: 'Bart Nieuwkoop', p: 'D' },
    { n: 'Givairo Read', p: 'D' },
    { n: 'Gijs Smal', p: 'D' },
    { n: 'Tsuyoshi Watanabe', p: 'D' },
    { n: 'Tijme Wessels', p: 'D' },
    { n: 'Tobias van den Elshout', p: 'M' },
    { n: 'Thijs Kraaijeveld', p: 'M' },
    { n: 'Jakub Moder', p: 'M' },
    { n: 'Jerayno Schaken', p: 'M' },
    { n: 'Sem Steijn', p: 'M' },
    { n: 'Oussama Targhaline', p: 'M' },
    { n: 'Luciano Valente', p: 'M' },
    { n: 'Charles Vanhoutte', p: 'M' },
    { n: 'Gjivai Zechiël', p: 'M' },
    { n: 'Gonçalo Borges', p: 'F' },
    { n: 'Gaoussou Diarra', p: 'F' },
    { n: 'Nacho Ferri', p: 'F' },
    { n: 'Anis Hadj Moussa', p: 'F' },
    { n: 'Reiss Nelson', p: 'F' },
    { n: 'Shaqueel Van Persie', p: 'F' },
    { n: 'Jivayno Zinhagel', p: 'F' },
  ],

  // sq20 — Lille (ESPN 166, fra.1) — 28 giocatori
  sq20: [
    { n: 'Arnaud Bodart', p: 'G' },
    { n: 'Orlando Gill', p: 'G' },
    { n: 'Berke Özer', p: 'G' },
    { n: 'Alexsandro', p: 'D' },
    { n: 'Isaac Cossier', p: 'D' },
    { n: 'Maxima Goffi', p: 'D' },
    { n: 'Nathan Ngoy', p: 'D' },
    { n: 'Tanguy Nianzou', p: 'D' },
    { n: 'Romain Perraud', p: 'D' },
    { n: 'Tiago Santos', p: 'D' },
    { n: 'Loun Srdanovic', p: 'D' },
    { n: 'Calvin Verdonk', p: 'D' },
    { n: 'Benjamin André', p: 'M' },
    { n: 'Nabil Bentaleb', p: 'M' },
    { n: 'Hákon Haraldsson', p: 'M' },
    { n: 'Maurits Kjaergaard', p: 'M' },
    { n: 'Ethan Mbappé', p: 'M' },
    { n: 'Ngal\'ayel Mukau', p: 'M' },
    { n: 'Dilane Bakwa', p: 'F' },
    { n: 'Mohamed Bayo', p: 'F' },
    { n: 'Soriba Diaoune', p: 'F' },
    { n: 'Olivier Giroud', p: 'F' },
    { n: 'Hamza Igmane', p: 'F' },
    { n: 'Tiago Morais', p: 'F' },
    { n: 'Basar Önal', p: 'F' },
    { n: 'Gaetan Perrin', p: 'F' },
    { n: 'Osame Sahraoui', p: 'F' },
    { n: 'Ayase Ueda', p: 'F' },
  ],

  // sq21 — Bodø/Glimt (ESPN 2980, nor.1) — 35 giocatori
  sq21: [
    { n: 'Martin Lund Andersen', p: 'G' },
    { n: 'Nikita Haykin', p: 'G' },
    { n: 'Julian Faye Lund', p: 'G' },
    { n: 'Isak Sjong', p: 'G' },
    { n: 'Haitam Aleesami', p: 'D' },
    { n: 'Fredrik André Bjørkan', p: 'D' },
    { n: 'Odin Bjørtuft', p: 'D' },
    { n: 'Jostein Gundersen', p: 'D' },
    { n: 'Matias Bobo Høgsæt Jaiteh', p: 'D' },
    { n: 'Isak Dybvik Määttä', p: 'D' },
    { n: 'Villads Nielsen', p: 'D' },
    { n: 'Mathias Olsen', p: 'D' },
    { n: 'Fredrik Sjøvold', p: 'D' },
    { n: 'Tobias Solbakken', p: 'D' },
    { n: 'Sondre Auklend', p: 'M' },
    { n: 'Patrick Berg', p: 'M' },
    { n: 'Ole Didrik Blomberg', p: 'M' },
    { n: 'Erling Eliassen', p: 'M' },
    { n: 'Hakon Evjen', p: 'M' },
    { n: 'Sondre Brunstad Fet', p: 'M' },
    { n: 'Jens Petter Hauge', p: 'M' },
    { n: 'Teo Ingilæ', p: 'M' },
    { n: 'Milton Käld', p: 'M' },
    { n: 'Joshua Kitolano', p: 'M' },
    { n: 'Joel Mvuka', p: 'M' },
    { n: 'Jesper Rabben Nygård', p: 'M' },
    { n: 'Magnus Riisnaes', p: 'M' },
    { n: 'Ulrik Saltnes', p: 'M' },
    { n: 'Kasper Johansen Solhaug', p: 'M' },
    { n: 'Levi Monsen Yeboah', p: 'M' },
    { n: 'Ola Brynhildsen', p: 'F' },
    { n: 'Hindrin Chooly', p: 'F' },
    { n: 'Andreas Helmersen', p: 'F' },
    { n: 'August Mikkelsen', p: 'F' },
    { n: 'Jakob Strand', p: 'F' },
  ],

  // sq22 — Napoli (ESPN 114, ita.1) — 27 giocatori
  sq22: [
    { n: 'Nikita Contini', p: 'G' },
    { n: 'Alex Meret', p: 'G' },
    { n: 'Vanja Milinkovic-Savic', p: 'G' },
    { n: 'Claudio Pugliese', p: 'G' },
    { n: 'Benoît Badiashile', p: 'D' },
    { n: 'Sam Beukema', p: 'D' },
    { n: 'Alessandro Buongiorno', p: 'D' },
    { n: 'Costantino Favasuli', p: 'D' },
    { n: 'Giovanni Di Lorenzo', p: 'D' },
    { n: 'Luca Marianucci', p: 'D' },
    { n: 'Rafa Marín', p: 'D' },
    { n: 'Mathías Olivera', p: 'D' },
    { n: 'Amir Rrahmani', p: 'D' },
    { n: 'Leonardo Spinazzola', p: 'D' },
    { n: 'Frank Anguissa', p: 'M' },
    { n: 'Kevin De Bruyne', p: 'M' },
    { n: 'Billy Gilmour', p: 'M' },
    { n: 'Stanislav Lobotka', p: 'M' },
    { n: 'Scott McTominay', p: 'M' },
    { n: 'Antonio Vergara', p: 'M' },
    { n: 'Giovane', p: 'F' },
    { n: 'Rasmus Højlund', p: 'F' },
    { n: 'Noa Lang', p: 'F' },
    { n: 'Lorenzo Lucca', p: 'F' },
    { n: 'David Neres', p: 'F' },
    { n: 'Matteo Politano', p: 'F' },
    { n: 'Alisson Santos', p: 'F' },
  ],

  // sq23 — RB Leipzig (ESPN 11420, ger.1) — 31 giocatori
  sq23: [
    { n: 'Ørjan Nyland', p: 'G' },
    { n: 'Maarten Vandevoordt', p: 'G' },
    { n: 'Leopold Zingerle', p: 'G' },
    { n: 'Ridle Baku', p: 'D' },
    { n: 'Maxime Estève', p: 'D' },
    { n: 'Max Finkgrafe', p: 'D' },
    { n: 'Benjamin Henrichs', p: 'D' },
    { n: 'Lukas Klostermann', p: 'D' },
    { n: 'Abdoul Koné', p: 'D' },
    { n: 'Castello Lukeba', p: 'D' },
    { n: 'Willi Orbán', p: 'D' },
    { n: 'David Raum', p: 'D' },
    { n: 'Neil El Aynaoui', p: 'M' },
    { n: 'Ezechiel Banzuzi', p: 'M' },
    { n: 'Christoph Baumgartner', p: 'M' },
    { n: 'Viggo Gebel', p: 'M' },
    { n: 'Benno Kaltefleiter', p: 'M' },
    { n: 'Andrija Maksimovic', p: 'M' },
    { n: 'Antonio Nusa', p: 'M' },
    { n: 'Assan Ouédraogo', p: 'M' },
    { n: 'Rocco Reitz', p: 'M' },
    { n: 'Nicolas Seiwald', p: 'M' },
    { n: 'Arthur Vermeeren', p: 'M' },
    { n: 'Johan Bakayoko', p: 'F' },
    { n: 'Tidiam Gomis', p: 'F' },
    { n: 'Brajan Gruda', p: 'F' },
    { n: 'Marc Guiu', p: 'F' },
    { n: 'Samba Konate', p: 'F' },
    { n: 'Christopher Nkunku', p: 'F' },
    { n: 'Rômulo', p: 'F' },
    { n: 'Sani Suleiman', p: 'F' },
  ],

  // sq24 — Villarreal (ESPN 102, esp.1) — 27 giocatori
  sq24: [
    { n: 'Rubén Gómez', p: 'G' },
    { n: 'Péter Gulácsi', p: 'G' },
    { n: 'Luiz Júnior', p: 'G' },
    { n: 'Yakiv Kinareykin', p: 'G' },
    { n: 'Sergi Cardona', p: 'D' },
    { n: 'Logan Costa', p: 'D' },
    { n: 'Juan Foyth', p: 'D' },
    { n: 'Alex Freeman', p: 'D' },
    { n: 'Santiago Mouriño', p: 'D' },
    { n: 'Pau Navarro', p: 'D' },
    { n: 'Carlos Romero', p: 'D' },
    { n: 'Renato Veiga', p: 'D' },
    { n: 'Santi Comesaña', p: 'M' },
    { n: 'Alassane Diatta', p: 'M' },
    { n: 'Pape Gueye', p: 'M' },
    { n: 'Carlos Macià', p: 'M' },
    { n: 'Alberto Moleiro', p: 'M' },
    { n: 'Nathan Saliba', p: 'M' },
    { n: 'Cheikh Ahmad Tidiane Thiam', p: 'M' },
    { n: 'Ilias Akhomach', p: 'F' },
    { n: 'Tajon Buchanan', p: 'F' },
    { n: 'Nizar El Jmili Ben Hamou', p: 'F' },
    { n: 'Georges Mikautadze', p: 'F' },
    { n: 'Gerard Moreno', p: 'F' },
    { n: 'Tani Oluwaseyi', p: 'F' },
    { n: 'Nicolas Pépé', p: 'F' },
    { n: 'Ayoze Pérez', p: 'F' },
  ],

  // sq25 — Fenerbahçe (ESPN 436, tur.1) — 32 giocatori
  sq25: [
    { n: 'Tarik Cetin', p: 'G' },
    { n: 'Ederson', p: 'G' },
    { n: 'Mert Günok', p: 'G' },
    { n: 'Kuzey Sapaz', p: 'G' },
    { n: 'Nathan Aké', p: 'D' },
    { n: 'Rodrigo Becão', p: 'D' },
    { n: 'Archie Brown', p: 'D' },
    { n: 'Yiğit Demir', p: 'D' },
    { n: 'Munir Mercan', p: 'D' },
    { n: 'Ognjen Mimovic', p: 'D' },
    { n: 'Mert Müldür', p: 'D' },
    { n: 'Jayden Oosterwolde', p: 'D' },
    { n: 'Kojo Peprah Oppong', p: 'D' },
    { n: 'Nélson Semedo', p: 'D' },
    { n: 'Milan Skriniar', p: 'D' },
    { n: 'Marco Asensio', p: 'M' },
    { n: 'Bartug Elmaz', p: 'M' },
    { n: 'Abdou Fall', p: 'M' },
    { n: 'Matteo Guendouzi', p: 'M' },
    { n: 'Irfan Can Kahveci', p: 'M' },
    { n: 'N\'Golo Kanté', p: 'M' },
    { n: 'Mert Yandas', p: 'M' },
    { n: 'Ismail Yüksek', p: 'M' },
    { n: 'Kerem Aktürkoglu', p: 'F' },
    { n: 'Oguz Aydin', p: 'F' },
    { n: 'Çagri Balta', p: 'F' },
    { n: 'Amara Diouf', p: 'F' },
    { n: 'Nene Dorgeles', p: 'F' },
    { n: 'Alaettin Ekici', p: 'F' },
    { n: 'Mason Greenwood', p: 'F' },
    { n: 'Romelu Lukaku', p: 'F' },
    { n: 'Vedat Muriqi', p: 'F' },
  ],

  // sq26 — Shakhtar Donetsk (ESPN 493, uefa.champions) — 33 giocatori
  sq26: [
    { n: 'Rostyslav Bahlai', p: 'G' },
    { n: 'Kiril Fesiun', p: 'G' },
    { n: 'Dmytro Riznyk', p: 'G' },
    { n: 'Denys Tvardovskyi', p: 'G' },
    { n: 'Vinicius Augusto', p: 'D' },
    { n: 'Irakli Azarovi', p: 'D' },
    { n: 'Valeriy Bondar', p: 'D' },
    { n: 'Alaa Ghram', p: 'D' },
    { n: 'Marlon', p: 'D' },
    { n: 'Alan Matturro', p: 'D' },
    { n: 'Mykola Matviyenko', p: 'D' },
    { n: 'Pedrinho', p: 'D' },
    { n: 'Bruninho', p: 'M' },
    { n: 'Eguinaldo', p: 'M' },
    { n: 'Lucas Ferreira', p: 'M' },
    { n: 'Marlon Gomes', p: 'M' },
    { n: 'Isaque', p: 'M' },
    { n: 'Oleksandr Karavaev', p: 'M' },
    { n: 'Dmytro Kryskiv', p: 'M' },
    { n: 'Gleiker Mendoza', p: 'M' },
    { n: 'Yehor Nazaryna', p: 'M' },
    { n: 'Newertton', p: 'M' },
    { n: 'Prosper Obah', p: 'M' },
    { n: 'Oleh Ocheretko', p: 'M' },
    { n: 'Pedrinho', p: 'M' },
    { n: 'Alisson Santana', p: 'M' },
    { n: 'Denys Smetana', p: 'M' },
    { n: 'Viktor Tsukanov', p: 'M' },
    { n: 'Kauã Elias', p: 'F' },
    { n: 'Luca Meirelles', p: 'F' },
    { n: 'Ryan Roberto', p: 'F' },
    { n: 'Gabriel Teixeira', p: 'F' },
    { n: 'Lassina Traoré', p: 'F' },
  ],

  // sq27 — Galatasaray (ESPN 432, tur.1) — 31 giocatori
  sq27: [
    { n: 'Enes Büyük', p: 'G' },
    { n: 'Ugurcan Çakir', p: 'G' },
    { n: 'Günay Güvenc', p: 'G' },
    { n: 'Arda Yilmaz', p: 'G' },
    { n: 'Jankat Yilmaz', p: 'G' },
    { n: 'Kaan Ayhan', p: 'D' },
    { n: 'Abdülkerim Bardakçi', p: 'D' },
    { n: 'El Chadaille Bitshiabu', p: 'D' },
    { n: 'Eren Elmali', p: 'D' },
    { n: 'Ismail Jakobs', p: 'D' },
    { n: 'Kazimcan Karatas', p: 'D' },
    { n: 'Davinson Sánchez', p: 'D' },
    { n: 'Wilfried Singo', p: 'D' },
    { n: 'Arda Ünyay', p: 'D' },
    { n: 'Eyüp Aydin', p: 'M' },
    { n: 'Alexey Batrakov', p: 'M' },
    { n: 'Ilkay Gündogan', p: 'M' },
    { n: 'Mario Lemina', p: 'M' },
    { n: 'Renato Nhaga', p: 'M' },
    { n: 'Gabriel Sara', p: 'M' },
    { n: 'Lucas Torreira', p: 'M' },
    { n: 'Lesley Ugochukwu', p: 'M' },
    { n: 'Yunus Akgün', p: 'F' },
    { n: 'Deniz Gül', p: 'F' },
    { n: 'Can Güner', p: 'F' },
    { n: 'Rafael Leão', p: 'F' },
    { n: 'Berat Lus', p: 'F' },
    { n: 'Victor Osimhen', p: 'F' },
    { n: 'Roland Sallai', p: 'F' },
    { n: 'Leroy Sané', p: 'F' },
    { n: 'Baris Alper Yilmaz', p: 'F' },
  ],

  // sq28 — Slavia Praha (ESPN 494, uefa.champions) — 31 giocatori
  sq28: [
    { n: 'Nazar Domchak', p: 'G' },
    { n: 'Ondrej Kolar', p: 'G' },
    { n: 'Jakub Markovic', p: 'G' },
    { n: 'Jindrich Stanek', p: 'G' },
    { n: 'Sahmkou Camara', p: 'D' },
    { n: 'Stepán Chaloupek', p: 'D' },
    { n: 'Tomás Holes', p: 'D' },
    { n: 'Samuel Isife', p: 'D' },
    { n: 'David Jurásek', p: 'D' },
    { n: 'Jakub Kolísek', p: 'D' },
    { n: 'Mikulás Konecny', p: 'D' },
    { n: 'Oskar Kubiak', p: 'D' },
    { n: 'Ange N\'Guessan', p: 'D' },
    { n: 'Igoh Ogbu', p: 'D' },
    { n: 'Eliás Piták', p: 'D' },
    { n: 'Tomás Vlcek', p: 'D' },
    { n: 'David Zima', p: 'D' },
    { n: 'Emmanuel Dennis Ayaosi', p: 'M' },
    { n: 'Toumani Diakité', p: 'M' },
    { n: 'Pavel Kacor', p: 'M' },
    { n: 'David Moses', p: 'M' },
    { n: 'Wiktor Nowak', p: 'M' },
    { n: 'Lukás Provod', p: 'M' },
    { n: 'Michal Sadílek', p: 'M' },
    { n: 'Youssoupha Sanyang', p: 'M' },
    { n: 'Mubarak Suleiman', p: 'M' },
    { n: 'Tomás Chorý', p: 'F' },
    { n: 'Mojmír Chytil', p: 'F' },
    { n: 'Adonija Bryan Ouanda', p: 'F' },
    { n: 'Ivan Schranz', p: 'F' },
    { n: 'Danijel Sturm', p: 'F' },
  ],

  // sq29 — Slovan Bratislava (ESPN 521, uefa.champions) — 36 giocatori
  sq29: [
    { n: 'Dávid Balog', p: 'G' },
    { n: 'Matus Macik', p: 'G' },
    { n: 'Aleksander Popovic', p: 'G' },
    { n: 'Dominik Takac', p: 'G' },
    { n: 'Kenan Bajric', p: 'D' },
    { n: 'César Blackman', p: 'D' },
    { n: 'Sandro Cruz', p: 'D' },
    { n: 'Samuel Kozlovsky', p: 'D' },
    { n: 'Svetozar Markovic', p: 'D' },
    { n: 'Jurij Medvedev', p: 'D' },
    { n: 'Matús Minka', p: 'D' },
    { n: 'Róbert Tománek', p: 'D' },
    { n: 'Kevin Wimmer', p: 'D' },
    { n: 'Tigran Barseghyan', p: 'M' },
    { n: 'Artur Gajdos', p: 'M' },
    { n: 'Leo Hofstädter', p: 'M' },
    { n: 'Rahim Ibrahim', p: 'M' },
    { n: 'Danylo Ignatenko', p: 'M' },
    { n: 'Manasse Kianga', p: 'M' },
    { n: 'Nino Marcelli', p: 'M' },
    { n: 'Alexej Maros', p: 'M' },
    { n: 'Cristian Martínez', p: 'M' },
    { n: 'Daiki Matsuoka', p: 'M' },
    { n: 'Alen Mustafic', p: 'M' },
    { n: 'Kelvin Ofori', p: 'M' },
    { n: 'Peter Pokorny', p: 'M' },
    { n: 'Alasana Yirajang', p: 'M' },
    { n: 'Suleiman Camara', p: 'F' },
    { n: 'Adam Canolli', p: 'F' },
    { n: 'Roman Cerepkai', p: 'F' },
    { n: 'Adam Griger', p: 'F' },
    { n: 'Mykola Kukharevych', p: 'F' },
    { n: 'Jakub Murko', p: 'F' },
    { n: 'Andraz Sporar', p: 'F' },
    { n: 'Matús Tomásko', p: 'F' },
    { n: 'Alex Veľký', p: 'F' },
  ],

  // sq30 — VfB Stuttgart (ESPN 134, ger.1) — 31 giocatori
  sq30: [
    { n: 'Fabian Bredlow', p: 'G' },
    { n: 'Stefan Drljaca', p: 'G' },
    { n: 'Marius Funk', p: 'G' },
    { n: 'Dennis Seimen', p: 'G' },
    { n: 'Lorenz Assignon', p: 'D' },
    { n: 'Jeff Chabot', p: 'D' },
    { n: 'Ameen Al Dakhil', p: 'D' },
    { n: 'Ramon Hendriks', p: 'D' },
    { n: 'Luca Jaquez', p: 'D' },
    { n: 'Finn Jeltsch', p: 'D' },
    { n: 'Maximilian Mittelstädt', p: 'D' },
    { n: 'Leonidas Stergiou', p: 'D' },
    { n: 'Josha Vagnoman', p: 'D' },
    { n: 'Dan-Axel Zagadou', p: 'D' },
    { n: 'Chris Führich', p: 'M' },
    { n: 'Atakan Karazor', p: 'M' },
    { n: 'Bilal El Khannouss', p: 'M' },
    { n: 'Jarzinho Malanga', p: 'M' },
    { n: 'Nikolas Nartey', p: 'M' },
    { n: 'Grischa Prömel', p: 'M' },
    { n: 'Yanik Spalt', p: 'M' },
    { n: 'Angelo Stiller', p: 'M' },
    { n: 'Ertugrul Yigit', p: 'M' },
    { n: 'Jeremy Arévalo', p: 'F' },
    { n: 'Ermedin Demirovic', p: 'F' },
    { n: 'Justin Diehl', p: 'F' },
    { n: 'Jamie Leweling', p: 'F' },
    { n: 'Dzenan Pejcinovic', p: 'F' },
    { n: 'Leo Sauer', p: 'F' },
    { n: 'Tiago Tomás', p: 'F' },
    { n: 'Deniz Undav', p: 'F' },
  ],

  // sq31 — AEK Athens (ESPN 887, gre.1) — 32 giocatori
  sq31: [
    { n: 'Marios Balamotis', p: 'G' },
    { n: 'Alberto Brignoli', p: 'G' },
    { n: 'Georgios Sarakasidis', p: 'G' },
    { n: 'Thomas Strakosha', p: 'G' },
    { n: 'Christos Alexiou', p: 'D' },
    { n: 'Spyros Christakopoulos', p: 'D' },
    { n: 'Martin Georgiev', p: 'D' },
    { n: 'Charalampos Lykogiannis', p: 'D' },
    { n: 'Harold Moukoudi', p: 'D' },
    { n: 'Stavros Pilios', p: 'D' },
    { n: 'Filipe Relvas', p: 'D' },
    { n: 'Lazaros Rota', p: 'D' },
    { n: 'Domagoj Vida', p: 'D' },
    { n: 'Kervin Arriaga', p: 'M' },
    { n: 'Mijat Gacinovic', p: 'M' },
    { n: 'Kaan Kairinen', p: 'M' },
    { n: 'Dimitrios Kaloskamis', p: 'M' },
    { n: 'Dereck Kutesa', p: 'M' },
    { n: 'Lovro Majer', p: 'M' },
    { n: 'Petros Mantalos', p: 'M' },
    { n: 'Razvan Marin', p: 'M' },
    { n: 'João Mário', p: 'M' },
    { n: 'Hakim Sahabo', p: 'M' },
    { n: 'Milán Vitális', p: 'M' },
    { n: 'Oleksandr Zubkov', p: 'M' },
    { n: 'Argyris Argyriou', p: 'F' },
    { n: 'Luka Jovic', p: 'F' },
    { n: 'Zois Karargyris', p: 'F' },
    { n: 'Aboubakary Koita', p: 'F' },
    { n: 'Frantz Pierrot', p: 'F' },
    { n: 'Barnabás Varga', p: 'F' },
    { n: 'Zini', p: 'F' },
  ],

  // sq32 — LASK (ESPN 4411, aut.1) — 28 giocatori
  sq32: [
    { n: 'Lukas Jungwirth', p: 'G' },
    { n: 'Fabian Schillinger', p: 'G' },
    { n: 'Tobias Schützenauer', p: 'G' },
    { n: 'Alemão', p: 'D' },
    { n: 'Andrés Andrade', p: 'D' },
    { n: 'George Bello', p: 'D' },
    { n: 'Melayro Bogarde', p: 'D' },
    { n: 'Yvan Dibango', p: 'D' },
    { n: 'Miguel Freckleton', p: 'D' },
    { n: 'Jonas Ilk', p: 'D' },
    { n: 'Kasper Jørgensen', p: 'D' },
    { n: 'Cheikne Kebe', p: 'D' },
    { n: 'Xavier Mbuyamba', p: 'D' },
    { n: 'Manoël Louis-Philippe Verhaeghe', p: 'D' },
    { n: 'Krystof Danek', p: 'M' },
    { n: 'Daniel Elfadli', p: 'M' },
    { n: 'Sascha Horvath', p: 'M' },
    { n: 'Mate Ivkovic', p: 'M' },
    { n: 'Christoph Lang', p: 'M' },
    { n: 'Robert Ljubicic', p: 'M' },
    { n: 'Alessandro Schöpf', p: 'M' },
    { n: 'Art Smakaj', p: 'M' },
    { n: 'Samuel Adeniran', p: 'F' },
    { n: 'Florian Flecker', p: 'F' },
    { n: 'Ramiz Harakate', p: 'F' },
    { n: 'Sasa Kalajdzic', p: 'F' },
    { n: 'Nael Kane', p: 'F' },
    { n: 'Moses Usor', p: 'F' },
  ],

  // sq33 — Como (ESPN 2572, ita.1) — 28 giocatori
  sq33: [
    { n: 'Jean Butez', p: 'G' },
    { n: 'Robert Sánchez', p: 'G' },
    { n: 'Mauro Vigorito', p: 'G' },
    { n: 'Trevoh Chalobah', p: 'D' },
    { n: 'Yan Couto', p: 'D' },
    { n: 'Alberto Dossena', p: 'D' },
    { n: 'Edoardo Goldaniga', p: 'D' },
    { n: 'Kaiki', p: 'D' },
    { n: 'Willy Kambwala', p: 'D' },
    { n: 'Marc-Oliver Kempf', p: 'D' },
    { n: 'Jacobo Ramón', p: 'D' },
    { n: 'Ivan Smolcic', p: 'D' },
    { n: 'Álex Valle', p: 'D' },
    { n: 'Martin Baturina', p: 'M' },
    { n: 'Maxence Caqueret', p: 'M' },
    { n: 'Riccardo Cassano', p: 'M' },
    { n: 'Lucas Da Cunha', p: 'M' },
    { n: 'Adrian Lahdo', p: 'M' },
    { n: 'Mattia Liberali', p: 'M' },
    { n: 'Luis Milla', p: 'M' },
    { n: 'Nico Paz', p: 'M' },
    { n: 'Máximo Perrone', p: 'M' },
    { n: 'Samuele Ricci', p: 'M' },
    { n: 'Jayden Addai', p: 'F' },
    { n: 'Assane Diao', p: 'F' },
    { n: 'Anastasios Douvikas', p: 'F' },
    { n: 'Moise Kean', p: 'F' },
    { n: 'Jesús Rodriguez', p: 'F' },
  ],

  // sq34 — Lens (ESPN 175, fra.1) — 31 giocatori
  sq34: [
    { n: 'Mathieu Gorgelin', p: 'G' },
    { n: 'Régis Gurtner', p: 'G' },
    { n: 'Ilan Jourdren', p: 'G' },
    { n: 'Robin Risser', p: 'G' },
    { n: 'Saud Abdulhamid', p: 'D' },
    { n: 'Ruben Aguilar', p: 'D' },
    { n: 'Kyllian Antonio', p: 'D' },
    { n: 'Samson Baidoo', p: 'D' },
    { n: 'Nidal Celik', p: 'D' },
    { n: 'Jhoanner Chavez', p: 'D' },
    { n: 'Pierre Ganiou', p: 'D' },
    { n: 'Jonathan Gradit', p: 'D' },
    { n: 'Maik Nawrocki', p: 'D' },
    { n: 'Souleymane Sagnan', p: 'D' },
    { n: 'Jean-Clair Todibo', p: 'D' },
    { n: 'Matthieu Udol', p: 'D' },
    { n: 'Andrija Bulatovic', p: 'M' },
    { n: 'Michaël Cuisance', p: 'M' },
    { n: 'Alpha Diallo', p: 'M' },
    { n: 'Amadou Haidara', p: 'M' },
    { n: 'Thorgan Hazard', p: 'M' },
    { n: 'Mezian Soares', p: 'M' },
    { n: 'Yassine Titraoui', p: 'M' },
    { n: 'Moussa Diarra', p: 'F' },
    { n: 'Odsonne Édouard', p: 'F' },
    { n: 'Franjo Ivanovic', p: 'F' },
    { n: 'Junior Kadile', p: 'F' },
    { n: 'Abdallah Sima', p: 'F' },
    { n: 'Michal Skoras', p: 'F' },
    { n: 'Florian Sotoca', p: 'F' },
    { n: 'Florian Thauvin', p: 'F' },
  ],

  // sq35 — Viking (ESPN 510, nor.1) — 41 giocatori
  sq35: [
    { n: 'Lubomir Belko', p: 'G' },
    { n: 'Elrend Jacobsen', p: 'G' },
    { n: 'Arild Ostbo', p: 'G' },
    { n: 'Vetle Auklend', p: 'D' },
    { n: 'Anders Baertelsen', p: 'D' },
    { n: 'Essien Bassey', p: 'D' },
    { n: 'Sondre Flem Bjørnshol', p: 'D' },
    { n: 'Jesper Daland', p: 'D' },
    { n: 'Jonathan Røksund Debes', p: 'D' },
    { n: 'Henrik Falchener', p: 'D' },
    { n: 'Herman Haugen', p: 'D' },
    { n: 'Kristoffer Haugen', p: 'D' },
    { n: 'Henrik Heggheim', p: 'D' },
    { n: 'Mats Sekse Johannesen', p: 'D' },
    { n: 'Anders Fiskum Larsen', p: 'D' },
    { n: 'Martin Ove Roseth', p: 'D' },
    { n: 'Gianni Stensness', p: 'D' },
    { n: 'Viljar Vevatne', p: 'D' },
    { n: 'Kristoffer Askildsen', p: 'M' },
    { n: 'Joe Bell', p: 'M' },
    { n: 'Henrik Rorvik Bjordal', p: 'M' },
    { n: 'Elias Dahman', p: 'M' },
    { n: 'Jakob Segadal Hansen', p: 'M' },
    { n: 'Henrik Kvelvane', p: 'M' },
    { n: 'Simen Kvia-Egeskog', p: 'M' },
    { n: 'Jacob Middelthon', p: 'M' },
    { n: 'Tobias Moi', p: 'M' },
    { n: 'Sondre Tveiten', p: 'M' },
    { n: 'Ola Visted', p: 'M' },
    { n: 'Sondre Bakken', p: 'F' },
    { n: 'Veton Berisha', p: 'F' },
    { n: 'Erik Botheim', p: 'F' },
    { n: 'Peter Christiansen', p: 'F' },
    { n: 'Amin Cosic', p: 'F' },
    { n: 'Nicholas D\'Agostino', p: 'F' },
    { n: 'Kelvin Frimpong', p: 'F' },
    { n: 'Niklas Fuglestad', p: 'F' },
    { n: 'Romano Postema', p: 'F' },
    { n: 'Christopher Salvesen-Svenning', p: 'F' },
    { n: 'Rasmus Gjelsvik Steigen', p: 'F' },
    { n: 'Zlatko Tripic', p: 'F' },
  ],

  // sq36 — Sabah (ESPN 21922, uefa.champions) — 31 giocatori
  sq36: [
    { n: 'Rauf Ayyubov', p: 'G' },
    { n: 'Ravan Mirzammadov', p: 'G' },
    { n: 'Stas Pokatilov', p: 'G' },
    { n: 'Amin Ramazanov', p: 'G' },
    { n: 'Júnior Almeida', p: 'D' },
    { n: 'Godfred Boakye', p: 'D' },
    { n: 'Japhet Dungus Bulus', p: 'D' },
    { n: 'Rahman Dashdamirov', p: 'D' },
    { n: 'Aden Mccarthy', p: 'D' },
    { n: 'Tellur Mutallimov', p: 'D' },
    { n: 'Cəfər Muxtarov', p: 'D' },
    { n: 'Tymoteusz Puchacz', p: 'D' },
    { n: 'Steve Solvet', p: 'D' },
    { n: 'Akim Zedadka', p: 'D' },
    { n: 'Khayal Aliyev', p: 'M' },
    { n: 'Rodrigo Fernandes', p: 'M' },
    { n: 'Sahin Ibrahimov', p: 'M' },
    { n: 'Aleksey Isayev', p: 'M' },
    { n: 'Zinédine Ould Khaled', p: 'M' },
    { n: 'Abdulakh Khaybulaev', p: 'M' },
    { n: 'Ivan Lepinjica', p: 'M' },
    { n: 'Kaheem Parris', p: 'M' },
    { n: 'Du Queiroz', p: 'M' },
    { n: 'Umarali Rakhmonaliev', p: 'M' },
    { n: 'Rauf Rustamli', p: 'M' },
    { n: 'Xander Severina', p: 'M' },
    { n: 'Younes Lachaab', p: 'F' },
    { n: 'Patrick Orphe M\'Bina', p: 'F' },
    { n: 'Joy Lance Mickels', p: 'F' },
    { n: 'Christian Nwachukwu', p: 'F' },
    { n: 'Veljko Simic', p: 'F' },
  ],
};
